"""empty message

Revision ID: 05bee7b71a2c
Revises: 7ae76918f510
Create Date: 2020-11-08 14:17:57.215035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bee7b71a2c'
down_revision = '7ae76918f510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dates', sa.String(), nullable=True),
    sa.Column('pfSysVols', sa.Float(), nullable=True),
    sa.Column('pfSpecVols', sa.Float(), nullable=True),
    sa.Column('pfVols', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Risk')
    # ### end Alembic commands ###
