"""empty message

Revision ID: 4f08aeae3cc1
Revises: 05bee7b71a2c
Create Date: 2020-11-08 14:30:19.763816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f08aeae3cc1'
down_revision = '05bee7b71a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BetasTime', sa.Column('mktVol', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BetasTime', 'mktVol')
    # ### end Alembic commands ###
