"""empty message

Revision ID: 77b1d0d8e8fb
Revises: e7b38a6472c4
Create Date: 2020-10-30 11:13:07.092467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b1d0d8e8fb'
down_revision = 'e7b38a6472c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BetasTime', sa.Column('dates', sa.String(), nullable=True))
    op.drop_column('BetasTime', 'quarter')
    op.drop_column('BetasTime', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BetasTime', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('BetasTime', sa.Column('quarter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('BetasTime', 'dates')
    # ### end Alembic commands ###
