"""empty message

Revision ID: 7a5a3ab16e5f
Revises: c84b7d8064e3
Create Date: 2020-11-14 12:39:53.151458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a5a3ab16e5f'
down_revision = 'c84b7d8064e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.String(), nullable=True),
    sa.Column('weights', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('getweights')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('getweights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alpha', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weights', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='getweights_pkey')
    )
    op.drop_table('weights')
    # ### end Alembic commands ###
