"""empty message

Revision ID: 7f519cd40123
Revises: 746eb79da0c4
Create Date: 2020-10-08 11:50:28.248377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f519cd40123'
down_revision = '746eb79da0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betas', sa.Column('mkt_vol', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('betas', 'mkt_vol')
    # ### end Alembic commands ###
