"""empty message

Revision ID: a8da1168c471
Revises: 7f519cd40123
Create Date: 2020-10-08 12:17:48.284330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8da1168c471'
down_revision = '7f519cd40123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mktvol', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market')
    # ### end Alembic commands ###
